# Graphs from Real-World Data, Milestone 1

A good place to start with a knowledge graph is to look at the source data and learn more about it and what it contains. For our use case we're going to work with NYC public data - tax records, deeds, and building permits (see the liveProject for more background on each of these data resources). Note that the source files are huge (the original tax files are 3.3 GB and have 139 columns!), so I've reduced the size and scope to make this more manageable. The project details all links to the source files if you want to explore more by yourself.

You're going to prepare two sets of files - one for a subset of Manhattan zipcodes and one for all of Manhattan. At the end of each data section you are asked questions about the data.

In [1]:
import os 

DATA_DIR = "./data"
INPUT_TAX_DATA_CSV = os.path.join(DATA_DIR, "tax.csv")
INPUT_DEED_DATA_CSV = os.path.join(DATA_DIR, "deed.csv")
INPUT_PERMIT_DATA_CSV = os.path.join(DATA_DIR, "permit.csv")

PERMIT_COLUMNS = [
    'BOROUGH', 
    'House #', 
    'Street Name', 
    'Zip Code',
    'Job #',
    'Block', 
    'Lot', 
    'Issuance Date', 
    "Owner's Business Type", 
    "Owner's Business Name", 
    "Owner's First Name", 
    "Owner's Last Name", 
    "Owner's House #", 
    "Owner's House Street Name", 
    "Owner's House City", 
    "Owner's House State", 
    "Owner's House Zip Code"
]

FINAL_SMALL_TAX_DATA_CSV = os.path.join(DATA_DIR, "tax_small_final.csv")
FINAL_SMALL_DEED_DATA_CSV = os.path.join(DATA_DIR, "deed_small_final.csv")
FINAL_SMALL_PERMIT_DATA_CSV = os.path.join(DATA_DIR, "permit_small_final.csv")

FINAL_LARGE_TAX_DATA_CSV = os.path.join(DATA_DIR, "tax_final.csv")
FINAL_LARGE_DEED_DATA_CSV = os.path.join(DATA_DIR, "deed_final.csv")
FINAL_LARGE_PERMIT_DATA_CSV = os.path.join(DATA_DIR, "permit_final.csv")

### 1. Load and filter tax records

The tax assessor file contains multiple years of records for all of the properties in Manhattan. This is going to be more than we need for this milestone, so we're going to filter the data:

* Filter to three zipcodes (ZIP_CODE) - 10001, 10016, 10118
* Filter to valid street addresses (i.e. non-null values of HOUSENUM_LO)

In [9]:
import polars as pl 
pl.Config.with_columns_kwargs = True

tax_small = (pl
    .read_csv(INPUT_TAX_DATA_CSV, ignore_errors=True)
    .filter(pl.col("ZIP_CODE").is_in([10001, 10016, 10118]))
    .with_columns(
        BORO = pl.col("BORO").cast(str), 
        BLOCK = pl.col("BLOCK").cast(str).str.zfill(5),
        LOT = pl.col("LOT").cast(str).str.zfill(4),
    )
    .filter(pl.col("HOUSENUM_LO").is_not_null())
    .filter(pl.col("HOUSENUM_HI").is_not_null())
    .with_column(
        pl.when(
            pl.col("APTNO").is_null()).then(pl.lit("")).otherwise(pl.col("APTNO")).alias("APTNO")
    )  
    .with_columns(
        BBL = pl.col("BORO") + pl.col("BLOCK") + pl.col("LOT"), 
        ADDRESS = pl.col("HOUSENUM_LO").cast(str) + " " + pl.col("STREET_NAME") + " " + pl.col("APTNO") + " NYC NY " + pl.col("ZIP_CODE").cast(str))
    .select([
        pl.col("BBL").alias("bbl"), 
        pl.col("OWNER").alias("tax_owner_name"),
        pl.col("ADDRESS").alias("tax_property_address")
     ] 
    )
)
tax_small

shape: (12989, 3)
┌────────────┬─────────────────────────────┬─────────────────────────────────────┐
│ bbl        ┆ tax_owner_name              ┆ tax_property_address                │
│ ---        ┆ ---                         ┆ ---                                 │
│ str        ┆ str                         ┆ str                                 │
╞════════════╪═════════════════════════════╪═════════════════════════════════════╡
│ 1005591001 ┆ WANG, MICHEL S              ┆ 137 EAST 37 STREET 1A NYC NY 100... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1005597502 ┆ UNAVAILABLE OWNER           ┆ 137 EAST 37 STREET  NYC NY 10016    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1007227501 ┆ UNAVAILABLE OWNER           ┆ 420 WEST 25 STREET  NYC NY 10001    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1008037502 ┆ NEWMARK,KNIGHT & FRANK      ┆ 301 7 AVENUE  NYC NY 10001          │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...                         ┆ ...                                 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1013141149 ┆ WILLIAM A. GEOGHAN, TRUSTEE ┆ 235 EAST 40 STREET 17I NYC NY 10... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1013141150 ┆ WILLIAM A. GEOGHAN, TRUSTEE ┆ 235 EAST 40 STREET 17J NYC NY 10... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1013141221 ┆ MICHAEL GOODMAN             ┆ 235 EAST 40 STREET 25E NYC NY 10... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1013141249 ┆ NANGIA, AMITABH             ┆ 235 EAST 40 STREET 28G NYC NY 10... │
└────────────┴─────────────────────────────┴─────────────────────────────────────┘

We're going to have separate entities for properties and addresses, so we need to add new columns that we can extract when loading the file into Neo4j. We'll need two new columns:

* BBL - as mentioned in the project, NYC organizes tax lots using the BOROUGH-BLOCK-LOT (BBL) system, where BOROUGH is a 1 digit number (BOROUGH = 1 is Manhattan), BLOCK is 5 digits, and LOT is 4 digits. We need to concat these columns into a single identifier.
  * For example, the Empire State Building is in Manhattan (borough = 1), block is 835 (zero-padded to 00835), and lot is 0041 (zero-padded to 0041), giving a BBL of 1008350041. 
* Address - many buildings have a range of street numbers, which is why the tax data contains HOUSENUM_LO (the lowest number in the range) and HOUSENUM_HI (the highest number in the range). For this exercise we're going to only use the low number for consistency. We're going to create a new address column by concatenating fields into this pattern: "\<HOUSENUM_LO\> \<STREET_NAME\> \<APTNO\> NYC NY \<ZIP_CODE\>"
  * Note that APTNO (apartment number) can be null; please filter out null values from the address string. 

In [10]:
tax_small.write_csv(FINAL_SMALL_TAX_DATA_CSV)

### 2. Load and filter property deeds

We're going to look at property deeds (i.e. transfer of real estate from one party to another). Normally this is split between five different datasets - for simplicity we've combined them into a single set of data.

We're going to repeat what we did before:

* Add a column for the property's BBL
* Add a column for Address - note that the document has two columns, one for property address and one for the new owner's address. Since we already have the property address, we're going to capture the owner's address (ADDRESS 1, ADDRESS 2, CITY, STATE, ZIP)
* Filter to the properties in our target zip codes (10001, 10016, 10118)

In [6]:
deed_small = (pl
           .read_csv(INPUT_DEED_DATA_CSV, ignore_errors=True)
           .unique()
           .filter(pl.col("ZIP").is_in([10001, 10016, 10118]))
           .with_columns(
               BOROUGH = pl.col("BOROUGH").cast(str),
               BLOCK = pl.col("BLOCK").cast(str).str.zfill(5),
               LOT = pl.col("LOT").cast(str).str.zfill(4),
           )
           .with_column(
               pl.when(pl.col("ADDRESS 2").is_null()).then(pl.lit(" ")).otherwise(pl.col("ADDRESS 2")).alias("ADDRESS 2") 
           )
           .with_columns(
               BBL = pl.col("BOROUGH") + pl.col("BLOCK") + pl.col("LOT"), 
               OWNER_ADDRESS = pl.col("ADDRESS 1") + " " + pl.col("ADDRESS 2") + pl.col("CITY") + " " + pl.col("STATE") + " " + pl.col("ZIP").cast(str),
           )
           .select([
               pl.col("BBL").alias("bbl"), 
               pl.col("DOCUMENT ID").alias("deed_id"), 
               pl.col("DOC. DATE").alias("deed_date"),
               pl.col("NAME").alias("deed_name"),
               pl.col("OWNER_ADDRESS").alias("deed_owner_address")
            ]
        )
)


In [20]:
deed_small

shape: (10845, 5)
┌────────────┬──────────────────┬────────────┬──────────────────────────┬──────────────────────────┐
│ bbl        ┆ deed_id          ┆ deed_date  ┆ deed_name                ┆ deed_owner_address       │
│ ---        ┆ ---              ┆ ---        ┆ ---                      ┆ ---                      │
│ str        ┆ i64              ┆ str        ┆ str                      ┆ str                      │
╞════════════╪══════════════════╪════════════╪══════════════════════════╪══════════════════════════╡
│ 1008942081 ┆ 2015071700095001 ┆ 07/07/2015 ┆ CYRIAC, GEORGE           ┆ 325 LEXINGTON AVENUE     │
│            ┆                  ┆            ┆                          ┆ NEW YORK N...            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1008942081 ┆ 2015071700095001 ┆ 07/07/2015 ┆ CYRIAC, CHACKUMKAL V     ┆ 325 LEXINGTON AVENUE     │
│            ┆                  ┆            ┆                          ┆ NEW YORK N...            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1008591119 ┆ 2015081101135002 ┆ 08/05/2015 ┆ 11 EAST 29TH STREET 46B, ┆ 240 FIFTH AVENUE  NEW    │
│            ┆                  ┆            ┆ LLC                      ┆ YORK NY 10...            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1012121103 ┆ 2015072300008002 ┆ 07/21/2015 ┆ ALLEN A. MEYER 2012      ┆ C/O SCOTT SEGAL, ESQ.,   │
│            ┆                  ┆            ┆ TRUST                    ┆ 10 EAST 4...             │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...              ┆ ...        ┆ ...                      ┆ ...                      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1009121246 ┆ 2022011801074002 ┆ 01/08/2022 ┆ CHEN, CLAUDIE S          ┆ 200 EAST 32ND STREET     │
│            ┆                  ┆            ┆                          ┆ #10E  NEW Y...           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1009121246 ┆ 2022011801074002 ┆ 01/08/2022 ┆ CHEN, CLAUDIE SHO-IN     ┆ 200 EAST 32ND STREET     │
│            ┆                  ┆            ┆                          ┆ #10E  NEW Y...           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1006991421 ┆ 2022011800285003 ┆ 01/06/2022 ┆ HAAS, CHRISTIAN          ┆ 527 WEST 27TH STREET     │
│            ┆                  ┆            ┆                          ┆ NEW YORK N...            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1006991421 ┆ 2022011800285003 ┆ 01/06/2022 ┆ DUARTE HAAS, SORAYA      ┆ 527 WEST 27TH STREET     │
│            ┆                  ┆            ┆                          ┆ NEW YORK N...            │
└────────────┴──────────────────┴────────────┴──────────────────────────┴──────────────────────────┘

In [21]:
deed_small.write_csv(FINAL_SMALL_DEED_DATA_CSV)

### 3. Load and filter building permits

Our last dataset - these are approved building permits that allow the property owner to make structural changes (e.g. add a window, install a new plumbing system, etc).

This is another one of those datasets with more data than we need - it captures information about the property owner, but also includes information about type of work being done and the person requesting the permit. This would be useful if we wanted to learn more about what type of property work is done in NYC and who is doing the work. 

* Add a column for the BBL
* Add a column for the owner's address
* Filter to the properties in our target zip codes (10001, 10016, 10118)

Note that we learn two things about the owner - the name of their business and their name! Let's also create a column for that, with convention "\<Owner's Last Name\>, \<Owner's First Name\>".

In [7]:
permit_small = (pl
           .read_csv(INPUT_PERMIT_DATA_CSV, ignore_errors=True)
           .unique()
           .filter(pl.col("Owner's House Zip Code").is_in([10001, 10016, 10118]))
           .with_columns(
               BOROUGH = pl.col("BOROUGH").cast(str),
               Block = pl.col("Block").cast(str).str.zfill(5),
               Lot = pl.col("Lot").cast(str).str.zfill(4),
           )
           .with_columns(
               BBL = pl.col("BOROUGH") + pl.col("Block") + pl.col("Lot"),
               OWNER_FULL_NAME = pl.col("Owner's First Name") + " " + pl.col("Owner's Last Name"), 
               OWNER_ADDRESS = pl.col("Owner's House #") + pl.col("Owner's House Street Name") + pl.col("Owner's House City") + pl.col("Owner's House State") + pl.col("Owner's House Zip Code")
           )
           .select([
               pl.col("BBL").alias("bbl"),
               pl.col("Issuance Date").alias("permit_date"),
               pl.col("OWNER_FULL_NAME").alias("permit_owner_name"),
               pl.col("OWNER_ADDRESS").alias("permit_owner_address"), 
               pl.col("Owner's Business Name").alias("permit_owner_business_name"),
               pl.col("Owner's Phone #").alias("permit_owner_phone"),
           ])
)


In [27]:
permit_small

shape: (3667, 6)
┌────────────────┬─────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ bbl            ┆ permit_date ┆ permit_owner_n ┆ permit_owner_a ┆ permit_owner_b ┆ permit_owner_p │
│ ---            ┆ ---         ┆ ame            ┆ ddress         ┆ usiness_name   ┆ hone           │
│ str            ┆ str         ┆ ---            ┆ ---            ┆ ---            ┆ ---            │
│                ┆             ┆ str            ┆ str            ┆ str            ┆ i64            │
╞════════════════╪═════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ MANHATTAN00803 ┆ 07/09/2020  ┆ JOANNA         ┆ 8056TH AVENUEM ┆ P.T REAL       ┆ 2129359184     │
│ 0041           ┆             ┆ THEOFANIS      ┆ ANHATTANNY1000 ┆ ESTATE HOLDING ┆                │
│                ┆             ┆                ┆ 1              ┆ LLC            ┆                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ MANHATTAN00804 ┆ 10/09/2020  ┆ HAE CHUNG      ┆ 533BERGEN      ┆ null           ┆ 2013963337     │
│ 0016           ┆             ┆                ┆ STREETNEW      ┆                ┆                │
│                ┆             ┆                ┆ YORKNY10001    ┆                ┆                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ MANHATTAN00830 ┆ 07/14/2020  ┆ SAMUEL         ┆ 8286TH         ┆ 828 6TH AVENUE ┆ 2126794065     │
│ 0080           ┆             ┆ ROSENBURG      ┆ AVENUENEW      ┆ CORP           ┆                │
│                ┆             ┆                ┆ YORKNY10001    ┆                ┆                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ MANHATTAN00564 ┆ 07/27/2020  ┆ PAUL           ┆ 37EAST 12TH    ┆ 37 E 12 STREET ┆ 2126134602     │
│ 7503           ┆             ┆ BRENSILBER     ┆ STREETNEW      ┆ CONDOMINIUMS   ┆                │
│                ┆             ┆                ┆ YORKNY1000...  ┆ LLC            ┆                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...            ┆ ...         ┆ ...            ┆ ...            ┆ ...            ┆ ...            │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ MANHATTAN00232 ┆ 2020-06-05  ┆ ROD KRITSBERG  ┆ 80PARK         ┆ 446 BROADWAY   ┆ 2123590743     │
│ 0006           ┆             ┆                ┆ AVENUENEW      ┆ OWNER LLC      ┆                │
│                ┆             ┆                ┆ YORKNY10016    ┆                ┆                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ MANHATTAN01505 ┆ 2020-06-05  ┆ THOMAS TEEPLE  ┆ C/O AKAM       ┆ 1120 FIFTH     ┆ 2129860001     │
│ 0001           ┆             ┆                ┆ 260MADISON     ┆ AVENUE         ┆                │
│                ┆             ┆                ┆ AVENUENEW      ┆ CORPORATION    ┆                │
│                ┆             ┆                ┆ YO...          ┆                ┆                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ MANHATTAN00460 ┆ 2020-06-05  ┆ LEOR SABET     ┆ 38WEST 31      ┆ 236 E 5 STREET ┆ 5165829978     │
│ 0029           ┆             ┆                ┆ STREETNEW      ┆ LLC            ┆                │
│                ┆             ┆                ┆ YORKNY10001    ┆                ┆                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ MANHATTAN00885 ┆ 03/01/2021  ┆ MICHAEL        ┆ 147LEXINGTON   ┆ 143/145        ┆ 2129668564     │
│ 7502           ┆             ┆ PLIGAVKO       ┆ AVENUE NEW     ┆ LEXINGTON LLC  ┆                │
│                ┆             ┆            

In [8]:
permit_small.write_csv(FINAL_SMALL_PERMIT_DATA_CSV)

### 4. Prepare the full set of data

Now that we're comfortable working with our records, we're going to create a second set of files that covers all of Manhattan. 

* Repeat the tax assessor data pull in Step 1, but this time don't filter on zip code
* Same for deeds and permits

In [31]:
tax = (
    pl.read_csv(INPUT_TAX_DATA_CSV, ignore_errors=True)
    .with_columns(
        BORO = pl.col("BORO").cast(str), 
        BLOCK = pl.col("BLOCK").cast(str).str.zfill(5),
        LOT = pl.col("LOT").cast(str).str.zfill(4),
    )
    .filter(pl.col("HOUSENUM_LO").is_not_null())
    .filter(pl.col("HOUSENUM_HI").is_not_null())
    .with_column(
        pl.when(
            pl.col("APTNO").is_null()).then(pl.lit("")).otherwise(pl.col("APTNO")).alias("APTNO")
    )   
    .with_columns(
        BBL = pl.col("BORO") + pl.col("BLOCK") + pl.col("LOT"), 
        ADDRESS = pl.col("HOUSENUM_LO").cast(str) + " " + pl.col("STREET_NAME") + " " + pl.col("APTNO") + " NYC NY " + pl.col("ZIP_CODE").cast(str)
)) 

tax.write_csv(FINAL_LARGE_TAX_DATA_CSV)

In [25]:
deed = (pl
           .read_csv(INPUT_DEED_DATA_CSV, ignore_errors=True)
           .unique()
           .with_column(
               pl.when(pl.col("ADDRESS 2").is_null()).then(pl.lit(" ")).otherwise(pl.col("ADDRESS 2")).alias("ADDRESS 2") 
           )
           .with_columns(
               BOROUGH = pl.col("BOROUGH").cast(str),
               BLOCK = pl.col("BLOCK").cast(str).str.zfill(5),
               LOT = pl.col("LOT").cast(str).str.zfill(4),
               OWNER_ADDRESS = pl.col("ADDRESS 1") + " " + pl.col("ADDRESS 2") + pl.col("CITY") + " " + pl.col("STATE") + " " + pl.col("ZIP").cast(str)
           ) 
)

deed.write_csv(FINAL_LARGE_DEED_DATA_CSV)

In [31]:
tax_small.filter(pl.col("tax_owner").str.contains("LLC"))

shape: (2547, 3)
┌────────────┬─────────────────────────────────────┬─────────────────────────────────────┐
│ bbl        ┆ tax_owner                           ┆ tax_address                         │
│ ---        ┆ ---                                 ┆ ---                                 │
│ str        ┆ str                                 ┆ str                                 │
╞════════════╪═════════════════════════════════════╪═════════════════════════════════════╡
│ 1006700070 ┆ BULGROUP COLORADO LLC               ┆ 231 11 AVENUE  NYC NY 10001         │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1006720001 ┆ RXR SL OWNER LLC                    ┆ 601 WEST 26 STREET  NYC NY 10001    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1006750001 ┆ 260 TWELFTH AVENUE HOLDINGS LLC     ┆ 260 12 AVENUE  NYC NY 10001         │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1006750012 ┆ WEST SIDE 11TH & 29TH LLC           ┆ 613 WEST 29 STREET  NYC NY 10001    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...                                 ┆ ...                                 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1009431733 ┆ SJ CORINTHIAN LLC                   ┆ 330 EAST 38 STREET 51E NYC NY 10... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1009431865 ┆ EAST 37 HOLDING LLC                 ┆ 345 EAST 37 STREET 318 NYC NY 10... │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1009681090 ┆ STEPHEN H. KAHN CPA LLC DEFINED ... ┆ 630 1 AVENUE 9G NYC NY 10016        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1009681218 ┆ 2013VM LLC                          ┆ 630 1 AVENUE 18G NYC NY 10016       │
└────────────┴─────────────────────────────────────┴─────────────────────────────────────┘